---
  sns:
    arn: arn:aws:sns:us-east-1:713321661885:Activity
    accessKeyId: AKIAJB7DZK35AFSZBXHA
    secretAccessKey: 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
    region: us-east-1
  sqs:
    accessKeyId: AKIAIQTAG25ELRUUAXGQ
    secretAccessKey: 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
    region: us-east-1
    queueUrl: https://sqs.us-east-1.amazonaws.com/713321661885/Activity
    dlqUrl: https://sqs.us-east-1.amazonaws.com/713321661885/ActivityDeadLetterQueue
    maxNumberOfMessages: 5
    waitTimeSeconds: 10
    visibilityTimeout: 30
  dynamo:
    accessKeyId: AKIAI25KEM5G2X6JRMUQ
    secretAccessKey: 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
    region: us-east-1
  dynamoDlq:
    accessKeyId: AKIAJ7I4KEZ2FIKN5KXA
    secretAccessKey: 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
    region: us-east-1
  metrics:
    accessKeyId: AKIAIPJY4UZRWZFTHKIA
    secretAccessKey: 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
    region: us-east-1
  snsQa:
    arn: arn:aws:sns:us-east-1:229683044909:Activity
    accessKeyId: AKIAIFI3YJ4DJ3DXGTGA
    secretAccessKey: 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
    region: us-east-1
  dynamoQa:
    accessKeyId: AKIAJQTBIP4W3ABKMNYA
    secretAccessKey: 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
    region: us-east-1
  sqsQa:
    accessKeyId: AKIAIL4PP7TGEPJB4JOA
    secretAccessKey: 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
    region: us-east-1
    queueUrl: https://sqs.us-east-1.amazonaws.com/229683044909/Activity
    dlqUrl: https://sqs.us-east-1.amazonaws.com/229683044909/ActivityDeadLetterQueue
    maxNumberOfMessages: 5
    waitTimeSeconds: 10
    visibilityTimeout: 30
  snsStg:
    arn: arn:aws:sns:us-east-1:791949374647:Activity_STG
    accessKeyId: AKIAJW663LU3TDTSK4RQ
    secretAccessKey: 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
    region: us-east-1
  dynamoStg:
    accessKeyId: AKIAIIEGH2XWVI5LKU3Q
    secretAccessKey: 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
    statementTable: Statement_STG
    region: us-east-1
  sqsStg:
    accessKeyId: AKIAIP2QMTR7OIMU27YA
    secretAccessKey: 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
    region: us-east-1
    queueUrl: https://sqs.us-east-1.amazonaws.com/791949374647/Activity_STG
    dlqUrl: https://sqs.us-east-1.amazonaws.com/791949374647/ActivityDeadLetterQueue_STG
    maxNumberOfMessages: 5
    waitTimeSeconds: 10
    visibilityTimeout: 30
  pollWaitTimeSeconds: 10
  mySql:
    host: localhost
    port: 8889
    user: elitecareer_usa
    password: As365827@
    database: activity
  detailedErrors: true
  accept:
    - application/json
  server:
    uri: localhost:4000
  routes:
    controllerRootUrl: '/api'
  logging:
    raygun:
      enabled: false
    logEntries:
      enabled: false
    stdout:
      enabled: true
      level: debug
  testPort: 5014
  env: dev
